version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.3.1

jobs:
  infer-own-config:
    docker:
      - image: cimg/go:1.20
    steps:
      - checkout
      - restore_cache:
          key: go-mod-{{ checksum "go.sum" }}
      - run:
          name: Download Go modules
          command: go mod download
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/go/pkg/mod
      - run:
          name: Build inference CLI
          command: go run ./cmd/inferconfig/inferconfig.go  > ./config.yml
      - continuation/continue:
          configuration_path: ./config.yml

workflows:
  inference:
    jobs:
      - infer-own-config
